{% set name = "pyscreenshot" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyscreenshot-{{ version }}.tar.gz
  sha256: 8c0e93f0aef66a6bfe55a86abfced6bd396ae4b4f6cc1e36f04a28ad2625594d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - easyprocess
    - entrypoint2
    - python-mss
    - jeepney

    # not listed upstream but needed
    - pillow

test:
  imports:
    - pyscreenshot
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Copy the contents of the screen to a Pillow image memory using various back-ends.
  home: https://github.com/ponty/pyscreenshot
  summary: python screenshot
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
